### ISSUE TITLE
jekyll-polyglot removes any images generated by jekyll_picture_tag

### ISSUE THREAD

**Issue by kylekirkby** [untra/polyglot#152]
Hi @untra ,

We're using the jekyll_picture_tag plugin to generate webp images for our sites. With the addition of `jekyll-polyglot` this has broken. Jekyll_picture_tag places the generated images inside the `assets/images` of the output site folder as the site is building. When the site build ends, it appears that jekyll-polylgot is removing all of these generated images and simply replacing the folder assets/images folder that exists in the base of the repo. 

Any ideas how we can stop this happening?

As a work-around I've had to set the output folder for generated images to a folder at the root of the repo (outside of the build folder). This then gets copied in as expected. 

```yml
# -------- jekyll_picture_tag --------
picture:
  nomarkdown: false
  suppress_warnings: true
  source: ""
  output: "../generated"
  relative_url: true
  disabled: false

# Jekyll-polyglot
i18n_enabled: true
languages: ["en", "ja"]
default_lang: "en"
exclude_from_localization:
  ["javascript", "images", "css", "public", "assets", "generated"]
parallel_localization: false
```
