### ISSUE TITLE
Assets folder is copied to another language folders.

### ISSUE THREAD

**Issue by tkosaka1976** [untra/polyglot#217]
When we use polyglot, if you set as "exclude_from_localizations: ["assets"]", but the asset folder also copy in the folder for another language.
(I'm setting "ja" as main lang and "en" as sub)

/assets
>   /js
>   /css
>   /img

/en
>    /assets
>>      /js
>>      /css
>>      /img

I noticed that the href tag code is not change to language specific (/assets/img/xxx.png) but files and folders always copied to the under the "en" folder.
The folder can be removed before the deployment but its more convenient where no copy.
In addition, robots.txt and sitemap.xml also copy to the under the "en" folder. It also convenient if there no copy.
Could you tell me, if there are another way to do this?
Probably there are no plug-in that can remove specific folders and files after the build.

**Comment by george-gca** [comment]
For my case my config is this:

```yml
languages: ["en-us", "pt-br"]
default_lang: "en-us"
exclude_from_localization: ["assets"]
lang_from_path: true
parallel_localization: false # I had problem with this on
```

and here is my assets outside and inside the other language:

```
ls _site/assets/
audio  bibliography  css  fonts  html  img  js  json  jupyter  libs  pdf  plotly  video  webfonts

ls _site/pt-br/assets/
img
```

Test your site with `parallel_localization: false`, see if it changes anything.

Now, probably the culprit on this is the `jekyll-imagemagick` plugin that doesn't do well with `polyglot`. Maybe this could be solved on `polyglot` side?
