### ISSUE TITLE
Not generating custom asset when `default_lang` != first language

### ISSUE THREAD

**Issue by george-gca** [untra/polyglot#233]
Here is the situation:

`_config.yml`
```yml
include: ["_scripts"]

languages: ["en-us", "pt-br"]
default_lang: "en-us"
exclude_from_localization: ["assets"]
lang_from_path: true
parallel_localization: false
```

`_scripts/scripts.js.liquid`
```liquid
---
permalink: /assets/js/scriptsss.js
---
...
```

It correctly creates

```bash
ls _site/assets/js/
cookies.js  levenshtein.js  pwa.js  scriptsss.js  theme.js

ls _site/pt-br/assets/js/
scriptsss.js
```

Everything is fine, `scriptsss.js` was correctly created in the assets dir for every language.

---

Now, if I change only the `default_lang` in `_config.yml` to `pt-br`, this happens:

```bash
ls _site/assets/js/
cookies.js  levenshtein.js  pwa.js  theme.js

ls _site/en-us/assets/js/
scriptsss.js
```

Any idea why it doesn't create the file `_site/assets/js/scriptsss.js`?
