### ISSUE TITLE
I18n_Headers for collections

### ISSUE THREAD

**Issue by leoplct** [untra/polyglot#241]
I see the I18n_Headers works for pages but not for collections. 

http://localhost:4000/it/docs/what-is-x/

This

`  {% I18n_Headers %}`

generates this 

```
  <meta http-equiv="Content-Language" content="it">
  <link rel="alternate" hreflang="en" href="http://localhost:4000/"/>
  <link rel="alternate" hreflang="zh" href="http://localhost:4000/zh/"/>
  <link rel="alternate" hreflang="it" href="http://localhost:4000/it/"/>
  <link rel="alternate" hreflang="fr" href="http://localhost:4000/fr/"/>
  <link rel="alternate" hreflang="de" href="http://localhost:4000/de/"/>
  <link rel="alternate" hreflang="es" href="http://localhost:4000/es/"/>
  <link rel="alternate" hreflang="pt" href="http://localhost:4000/pt/"/>
  <link rel="alternate" hreflang="ja" href="http://localhost:4000/ja/"/>
  <link rel="alternate" hreflang="ar" href="http://localhost:4000/ar/"/>
```

instead I expect

  <meta http-equiv="Content-Language" content="it">
  <link rel="alternate" hreflang="en" href="http://localhost:4000/docs/what-is-x"/>
  <link rel="alternate" hreflang="zh" href="http://localhost:4000/zh/docs/what-is-x"/>
  <link rel="alternate" hreflang="it" href="http://localhost:4000/it/docs/what-is-x"/>
  <link rel="alternate" hreflang="fr" href="http://localhost:4000/fr/docs/what-is-x"/>
  <link rel="alternate" hreflang="de" href="http://localhost:4000/de/docs/what-is-x"/>
  <link rel="alternate" hreflang="es" href="http://localhost:4000/es/docs/what-is-x"/>
  <link rel="alternate" hreflang="pt" href="http://localhost:4000/pt/docs/what-is-x"/>
  <link rel="alternate" hreflang="ja" href="http://localhost:4000/ja/docs/what-is-x"/>
  <link rel="alternate" hreflang="ar" href="http://localhost:4000/ar/docs/what-is-x"/>

**_docs/en/what-is.md**
```
rank: 1
section: Introduction
title: What is X?
page_id: what-is-X
```

**_docs/it/what-is.md**
```
rank: 1
section: Introduction
title: Cos'è X?
permalink: cosa-x
page_id: what-is-x
```

_config.yml
```
languages: ["en", "zh", "it", "fr", "de", "es", "pt", "ja",  "ar"]
default_lang: "en"
exclude_from_localization: [ "assets", "favicon",  "sitemap",  "javascript", "images", "css", "public"]
parallel_localization: true
lang_from_path: true

collections:
  docs:
    output: true
    sort_by: rank
    permalink: /docs/:title/
```
