### ISSUE TITLE
Relativizing the URLs yields error message

### ISSUE THREAD

**Issue by publicimageltd** [untra/polyglot#30]
I've added `jekyll polyglott` to my website (theme: minimal mistakes). When I build the site, I get an error message (output attached): [trace.txt](https://github.com/untra/polyglot/files/396178/trace.txt)

Another problem is that I even do not understand how I can check whether the mechanism for creating the urls works. My assumption is that, given I define the two languages "de" and "en" in `_config.yml`, there is prefix added to the site url, such as: "base-url.com/de/page.html", where page.html is the permanent link defined in the front matter of the associated page file. Is that right? If this is the expected behavior, the error above definitely breaks the whole thing -- there are no prefixes. Normal URLs work fine, though.

**Comment by untra** [comment]
```
/home/jv/.gem/ruby/2.3.0/gems/jekyll-polyglot-1.2.2/lib/jekyll/polyglot/patches/jekyll/site.rb:115:
in `relative_url_regex': target of repeat operator is not specified:
/href=\"\/((?:(?!*.sublime-project\/)(?!*.sublime-workspace\/)(?!.asset-cache\/)(?!.bundle\/)(?!.jekyll-assets-cache\/)(?!.sass-cache\/)(?!assets\/js\/plugins\/)(?!assets\/js\/_main.js\/)(?!assets\/js\/vendor\/)(?!Capfile\/)(?!CHANGELOG\/)(?!config\/)(?!Gemfile\/)(?!Gruntfile.js\/)(?!gulpfile.js\/)(?!LICENSE\/)(?!log\/)(?!node_modules\/)(?!package.json\/)(?!Rakefile\/)(?!README\/)(?!tmp\/)(?!javascript\/)(?!images\/)(?!css\/)[^,'\"\s\/?\.#]+\.?)*(?:\/[^\]\[\)\(\"\'\s]*)?)\"/
```
The error you are getting is from the regex polyglot uses to relativize urls being malformed .This regex is generated from values specified in your `exclude_from_localization`.

Can you post the part of your _config.yml with your polyglot options? I think a string in your `exclude_from_localization` list is causing this error.

Thanks!
-@untra

**Comment by publicimageltd** [comment]
Here is the relevant passage from `_config.yml`:

```yaml
languages: ["de", "en"]
default_lang: "de"
exclude_from_localization: ["javascript", "images", "css"]
parallel_localization: true
```

Thanks for the fast reaction! 
**@pil**

**Comment by untra** [comment]
Actually, I take that back; The relativized url regex is also formed from your `excludes` in your `_config.yml`.

From what the error message says, your excludes has
```
*.sublime-project
*.sublime-workspace
```
in it. I think Jekyll only recently began supporting wildcards in `_config` (yay! 😃 ), but the `*.` make for an invalid regex expression (boo! 😦 ), which is what causes this to fail.

I think this change in acceptable excluded files emerged somewhere in the development of Jekyll 3.2 which just released (and which I think you're using). This is definitely a bug on my part, but will take some extra tests and development to be sure the wildcards don't cause future problems. Good find!

A temporary fix is to avoid the wildcards in your `excludes` by giving explicit filenames to these files (actually I think `.sublime-project` and `.sublime-workspace` are hidden files, and dont have prefixes needing a wildcard before them. You should remove those and be fine).

Let me know if that helps!
Cheers,
@untra

**Comment by publicimageltd** [comment]
Yep! That's been it! Deleting the wildcards did the job. Thanks a lot! That was fast & accurate.

I encountered a new problem: Even though I have defined `de` as the default language, the cv page with `lang: de` in the front matter is mapped to the permalink `/en/cv.html`.

And you know what? Everything's correct if I swap the order of the languages in `config.yml`.

That's how it used to be:

```yaml
languages: ["de", "en"]
default_lang: "de"
exclude_from_localization: ["javascript", "images", "css"]
parallel_localization: true
```

Accessing `/en/cv.html` returns the german page.

Then I change to:

```yaml
languages: ["en", "de"]
default_lang: "de"
exclude_from_localization: ["javascript", "images", "css"]
parallel_localization: true
```

...and everything works fine -- `/de/cv.html` correctly returns the page with `lang: de`.

That's actually a new issue, but I'm closing the comment now since there's a workaround available right now. Thanks again!

@pil
