### ISSUE TITLE
Could not configure localized pages

### ISSUE THREAD

**Issue by publicimageltd** [untra/polyglot#31]
I'm trying to set up a CV in both english and german. This is my `_config.yml`:

```yaml
languages: ["de", "en"]
default_lang: "de"
exclude_from_localization: ["javascript", "images", "css"]
parallel_localization: true
```

I have two files, `cv.md` and `cv_englisch.md`, which both have the appropriate language set in the front matter.

And this is the result:

Request | Jekyll server returns
----- | -----
http://127.0.0.1:4000/en/cv.html | The english page
http://127.0.0.1:4000/de/cv.html | Page not found
http://127.0.0.1:4000/cv.html | The german page 

So the english prefix works, but not the german. Behavior does not change if I remove the setting for the default language.

I'm using jekyll 3.2.0

Any ideas?
