### ISSUE TITLE
site translation broken after pushing to gh-pages

### ISSUE THREAD

**Issue by cntlsn** [untra/polyglot#75]
Hi Untra,

After merging my `polyglot` branch to `gh-pages` the site is not able to display all the translated strings, nor in default or `/en/` language.
Actually, when trying to reach the not-default `website.com/en/` I get a 404
You can check the website [here](https://opencarecc.github.io/rampette/)

So far I have tried to:
- remove the CNAME
- remove the `data_dir: ./_data` and `destination:  ./_site` from `_config.yml`
- set `parallel_localization: false` in `_config.yml`

None of the above helped...

Any idea how to proceed?
Thanks a lot for your help.

**Comment by cntlsn** [comment]
Alright, I just saw this issue https://github.com/untra/polyglot/issues/64
:(

Any news on this?

**Comment by untra** [comment]
Unfortunately until we can get a multi languages plugin whitelisted, you cannot use polyglot with GitHub pages. Sorry 😅

However I am starting work on version 2.0.0, which I hope to get whitelisted in the future. Currently looking at these threads:
https://github.com/github/pages-gem/issues/401#issuecomment-325578751

If you leave this issue open I'll keep you updated 👍
Cheers,
Samuel Volin

**Comment by cntlsn** [comment]
Thanks Untra, I have thumbed-up your requests to maybe raise some attention on the topic.

I will leave the issue open so I can get updates sure.
But may I suggest to highlight on the readme that the plugin is not whitelisted?
I think it would be very convenient for people to know that in advance before spending hours on it, like I just did ;)

Thank you for your work, I hope it will get whitelisted soon.
Cheers

**Comment by basementcz** [comment]
Have the same problem :(

**Comment by basementcz** [comment]
@cntlsn I migrated my github pages to gitlab page and it is possible to use polyglot there.

**Comment by cntlsn** [comment]
hi @basementcz thx for your input, I will have a look.
I couldn't move my repo from github so I created a manual way to handle translations by following/hacking this approach: https://www.sylvaindurand.org/making-jekyll-multilingual/

**Comment by ZakCodes** [comment]
GitHub Pages doesn't accept many plugins, so if you want to do anything serious with Jekyll you pretty much have to build your site locally or with any CI system and then push it to your GitHub Pages branch.  

[Here's the documentation from TravisCI on how to do this](https://docs.travis-ci.com/user/deployment/pages/). Don't skip the step where you have to **manually** generate and register a private token for TravisCI. 

[Here's also my configuration with the build step if that helps](https://github.com/cyberquebec-org/cyberquebec-org.github.io/blob/source/.travis.yml). Works like a charm for me. My configuration is a little special because I had to push to the `master` branch instead of the `gh-pages` branch because I'm using it for the root of the GitHub Pages website. I also have to use another branch than `master` for the source code, so I used the `source` branch and I set it as the default branch for the project so this one would show up on my project's homepage instead of `master`.

**Comment by george-gca** [comment]
This [can be done nowadays](https://george-gca.github.io/multi-language-al-folio/) by building your site and publishing it with GitHub actions. Check [my template](https://github.com/george-gca/multi-language-al-folio), or more specifically the [GitHub action responsible for building and publishing it](https://github.com/george-gca/multi-language-al-folio/blob/main/.github/workflows/deploy.yml).

**Comment by meansoup** [comment]
@george-gca Hello george-gca I wanted to use your github action.
Can you explain about it?
I thought it works with `[deploy.yml](https://github.com/george-gca/multi-language-al-folio/blob/main/.github/workflows/deploy.yml)` but, in your actions, i show `pages build and deployment`

**Comment by george-gca** [comment]
But they are the same thing. Internally the [JamesIves/github-pages-deploy-action](https://github.com/JamesIves/github-pages-deploy-action) is used, which is the action that actually uploads the site correctly. These are the minimum steps required:

```yml
      - name: Checkout 🛎️
        uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2.2"
          bundler-cache: true
      - name: Install and Build 🔧
        run: |
          export JEKYLL_ENV=production
          bundle exec jekyll build --lsi
      - name: Deploy 🚀
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: _site
```

Meaning, get the code, setup the build environment, build the site, and upload the generated `_site/` directory to GitHub pages.
