### ISSUE TITLE
Adding a third language breaks the plugin

### ISSUE THREAD

**Issue by bernardomed** [untra/polyglot#83]
I have 3 different languages on my site.

When I had 2 languages working fine but when I needed to add the third, the landing page won't compile.

This is how my _config.yml is set:

```
# Localisation
languages: ["en", "it", "es"]
default_lang: "xx"
exclude_from_localization: ["javascript", "images", "css"]
parallel_localization: true

index:
  en: index.html
  it: indice.html
  es: inicio.html

```

As you can see, I have referenced different index files for each language.

Each language index file has a front matter header like this:

```
---
layout: home-es
ref: index
lang: es
---
```

Then the related home has its front matter like this:
```
---
layout: default-es
lang: es
---
```

And finally, the related default front matter is this:

```
---
layout: default-es
lang: es
---
```
If anyone has a suggestion on how to make the third language render, I'll be more than grateful.
